### ISSUE TITLE
v. 3.38.3 Publish sound conception

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#114]
The difference between the outer and inner envelope is not really clear to me.

Right now the sound seems to be at 100% in the inner envelope. However the sound does not stop at the outer envelope. Rather it continues for ever after. 
![image](https://github.com/Archtica/RADii/assets/45074510/356f5883-608f-42a6-9a37-bb35f9712caf)

I would add (i know always adding :D) an "outer sound level" and "inner sound level" input,  this way the sound transition could be controlled, since now all sound slowly fades. Every door to a loud room is a good example how quickly sound can decrease.
 input.
 In the default this would mean a 100 to 0 Decrease between the envelopes.
 
 Also i would make the sound inside the inner envelope always non spacial. In my experience, once you are very close or "inside" a soundspace" the directionality is not recognizable. If someone wants to keep the directionality they could make a smaller source and thereby not letting you "inside".

**Comment by Archtica** [comment]
Hi G, thank you for your explanation. It's a difficult thing. I worked with it all night and I think I have a solution. The attenuation of the sound follows a natural logarithmic decay as it is now. This means even at a distance you can hear some parts of the sound just like in reality if you are in open space. Last night I worked with a cutoff of sound at the outer envelope and if you don't scale the envelope correctly it sounds strange to the ear. F.ex moving up to a group of people talking with a small outer envelope would cause the sound to unnaturally appear just when you get close to them. If they were behind a door this would make sense because there is something blocking the natural movement of sound.
What I came up with is a toggle on the component called "cutoff" if not on, the sound will travel naturally and the outer envelope has no effect other than giving the sound an origin. The inner still defines the volume at 100%. If cut off is on, the sound will be cut off exactly at the outter envelop and gradually rise exponentially as you get closer to the inner. I moved the trigger to the inner envelope because it doesn't make sense to have it at the outer, where it also cuts off 100%. I think this works really well.
I will send you and update soon to test.

**Comment by gesievi** [comment]
Hello Thomas, very interesting to read about your experiments. Looking forward to see your proposal. 
If i understand you correctly we have two situations:

1. Natural decay 0 to 100 %
2. Cutoffs x>0 to 100

For the natural decay i would still propose to have the volume regulate between the inner to the outer boundary from 0 to 100 such as that when you reach the outer boundary the sound is so faint that you dont realise it ended. I am proposing this because it makes the control and precise placement of sounds visually understandable. The way it works right now is kind of open ended. Really curious to see if that works with your cutoff proposal.

Have a nice Day.

**Comment by Archtica** [comment]
Hi G, my thought is that "cutoff on" will work like your diagram with a complete cutoff at the outer envelope. No cutoff and the sounds will naturally decay based on how sound travels in space. The decay is relative to the distance like below. I will show it in a video.
[Decay](https://www.acoustical.co.uk/distance-attenuation/how-sound-reduces-with-distance-from-a-point-source/)

![image](https://github.com/Archtica/RADii/assets/33350816/ec81a8da-a856-4c39-b5fc-048ba851d95b)

![image](https://github.com/Archtica/RADii/assets/33350816/18d472c3-f6d9-4bb5-a64f-63bc17e0847b)
