### ISSUE TITLE
v 3.38.4b Paint Vertex 

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#116]
Paint vertex only works with images, it would be great and was expected by our students that a mono colour could be applied as well.

**Comment by Archtica** [comment]
Right now if no material is available on a referenced geometry it will skip it.
I just didn't think that would be something that would be wanted since you can paint meshes within GH itself. Just use the swatch component:

![image](https://github.com/Archtica/RADii/assets/33350816/718c05c1-0808-4421-b177-66143e7aa541)

On the point cloud parameter input if a mesh has no vertex coloring it wil paint the point cloud by the color of the object. This will create a uniform color.

**Comment by gesievi** [comment]
you are completly right, the paint mesh component does this already. this is a redundant request of mine. Jonas told me about it later.
