### ISSUE TITLE
v 38.6 publish animation save to cloud clears content

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#127]
Animations that are saved to the cloud clear the content they are send with. this results in cloud files that are 0mb.
When sending the content separately and then the animations it does not work. 
Publishing live works fine.
![image](https://github.com/Archtica/RADii/assets/45074510/d3703057-d952-47a5-b220-7a6783346a7d)

**Comment by Archtica** [comment]
I just tried saving some geometry and an animation and everything is fine. Maybe it is because some of your entwines are creating null values and I need to check for that.
Can you just try and enable "flattening" on the save component content input. I think that will fix it.

![image](https://github.com/Archtica/RADii/assets/33350816/4f3b7b6d-c045-4eab-bc71-156512cf3d01)

**Comment by Archtica** [comment]
By the way, if you are annimating content, the content needs to be added to the save component before the animation otherwise the animation wont find the content. Something I don't check for. In the scenario component I sort the content based on type. I need to do that with saving too.

**Comment by Archtica** [comment]
fixed
