### ISSUE TITLE
Publish material issue warning missing texture

### ISSUE THREAD

**Issue by gesievi** [Archtica/Radii#129]
Right now finding a missing or corruped texture is quiet difficult at times when the component is giving the error.
It would be great if they could output a list of missing files.
![grafik](https://github.com/Archtica/RADii/assets/45074510/43cf655b-61a3-40d7-b937-b453c1dfc5ce)

**Comment by Archtica** [comment]
I check if the path to the image file is valid and the reference is set otherwise it will throw that error. Also there is a solution exception which shouldn't be there. I should print the name of the material that has the issue, but I'm also interested in why it cannot find it. Does the texture work in Rhino?

**Comment by Archtica** [comment]
Is it possible to send the rhino file to me or is it too big?

**Comment by gesievi** [comment]
I have encountered this bug a few times not. It could have something to do with files that are saved on a server and then accessed. Rhino seems to be able to pull them nonetheless but radii throws this error. it would be fine to do so but it blocks all subsequent textures from being applied in radii. An error message that uploads all the non corrupted ones would be better. 
I can send you the file next time i encounter it.

**Comment by Archtica** [comment]
Fixed in next version with a notification in the log about which textures are the problem
