### ISSUE TITLE
AR Oculus: Origin Problem

### ISSUE THREAD

**Issue by jonashaldemann** [Archtica/Radii#31]
When more than 2 Headsets are in the same AR Scene and one Headset resets the Origin (3 sec Oculus Button) to reset/match the orientation of the Scene, this sometimes affects some of the other Headsets: We have noticed that suddenly the viewpoint of others changes, for example they are suddenly 1 meter higher or a few meters shifted.

**Comment by Archtica** [comment]
Hi Jonas, this has been fixed in the next release. I discovered that the user origin would conflict with geometry when moved across them like with a scene reset. This should be fixed in the next release, but please test it again when I upload it.
I have also made it so that the yellow user origin can be switched off so it's not always in the scene
